### ISSUE TITLE
Adding Ze Zhang to Karl's group

### ISSUE THREAD

**Issue by lucassalas** [immunomethylomics/immunomethylomics.github.io#1]
Hi Alexander,

I was trying to pull a new member to the group Ze Zhang ze_zhang@brown.edu  @zzhang23 will be helping Karl in his team.

Is it possible to add him to the github? I have not been working on github in a while. So not sure how can I add him to that group.

Thanks

**Comment by AlexanderTitus** [comment]
Completed
